services:
  postgres-db:
    image: postgres:15                
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${PG_USER}       
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_DB: ${PG_DATABASE}     
    ports:
      - "5432:5432"                    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .                      
      dockerfile: Dockerfile           
    container_name: nextjs-app
    environment:
      PG_USER: ${PG_USER}               
      PG_PASSWORD: ${PG_PASSWORD}       
      PG_HOST: ${PG_HOST}               
      PG_DATABASE: ${PG_DATABASE}       
      PG_PORT: ${PG_PORT}               
    ports:
      - "3000:3000"                    
    depends_on:
      - postgres-db                  
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
