services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres_db
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: postgres_db
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      NEXT_PUBLIC_API_URL: http://web:3000/api
      PRISMA_SCHEMA_PATH: ./prisma/schema.prisma
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    volumes:
      - .:/app
    command: npm run dev
    container_name: web

volumes:
  pgdata:
