version: '3.8'

services:
  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend 
    networks:
      - app-network

  backend:
    build:
      context: ./server 
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      - POSTGRES_USER=lucasmsardi
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=my_new_database
      - POSTGRES_HOST=postgres-db 
    ports:
      - "8080:8080" 
    depends_on:
      - postgres-db 
    networks:
      - app-network

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: lucasmsardi
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: my_new_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
