services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: postgres
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      NEXT_PUBLIC_API_URL: http://web:3000/api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata:
