services:
  postgres-db:
    image: postgres:15                
    container_name: postgres-db
    environment:
      POSTGRES_USER: my_user           
      POSTGRES_PASSWORD: my_password  
      POSTGRES_DB: my_database        
    ports:
      - "5432:5432"                  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .                    
      dockerfile: Dockerfile         
    container_name: nextjs-app
    environment:
      PG_USER: my_user
      PG_PASSWORD: my_password
      PG_HOST: postgres-db            
      PG_DATABASE: my_database
      PG_PORT: 5432
    ports:
      - "3000:3000"                  
    depends_on:
      - postgres-db                  
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
